POST http://localhost:5000/api/v1/transfers
Content-Type: application/json

{
    "reference": "TR00001",
    "transferFrom": 2,
    "transferTo": 3,
    "items": [
        {
            "itemId": "P004279",
            "amount": 10
        }
    ]
}
###

### Update Transfer Status to "Completed"
PUT http://localhost:5000/api/v1/transfers/7/status
Content-Type: application/json

"Completed"
###

PUT http://localhost:5000/api/v1/transfers/7/status
Content-Type: application/json

"InProgress"
###