POST http://localhost:5000/api/v1/transfers
Content-Type: application/json

{
    "reference": "TR00001",
    "transferFrom": 1,
    "transferTo": 2,
    "items": [
        {
            "itemId": "P000451",
            "amount": 10
        }
    ]
}
###

PUT http://localhost:5000/api/v1/transfers/1/status=Complete