POST http://localhost:5000/api/v1/transfers
Content-Type: application/json

{
    "reference": "TR00001",
    "transfer_from": 1,
    "transfer_to": 2,
    "items": [
        {
            "item_id": "P000451",
            "amount": 10
        }
    ]
}